# Generated by Django 4.1 on 2023-08-31 16:36

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Обложка')),
                ('video_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_videos', to='feed.theme')),
            ],
            options={
                'verbose_name': 'Видео',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VideoTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основная')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.theme')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.video')),
            ],
            options={
                'verbose_name': 'Тема видео',
                'verbose_name_plural': 'Темы видео',
                'ordering': ['theme__name'],
                'unique_together': {('video', 'theme')},
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
