# Generated by Django 3.1.2 on 2023-09-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['id'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
