# Generated by Django 3.1.2 on 2023-09-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20230901_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='videos_uploaded'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Обложка'),
        ),
    ]
