# Generated by Django 3.1.2 on 2023-09-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20230901_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='videos_uploaded', verbose_name='Видеофайл'),
        ),
    ]
