# Generated by Django 3.1.2 on 2023-09-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20230901_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_hash',
            field=models.CharField(db_index=True, default=None, max_length=32, unique=True, verbose_name='Хэш видео'),
        ),
    ]
