# Generated by Django 3.1.2 on 2023-09-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_video_video_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_hash',
            field=models.CharField(db_index=True, default=None, editable=False, max_length=32, unique=True, verbose_name='Хэш видео'),
        ),
    ]
